CXXFLAGS += -O3
CXXFLAGS += -std=c++17
CXXFLAGS += -I/home/atraore/gpi/try_gpi/gspc-gromovwitten/build_dir
CXXFLAGS += -I/home/atraore/gpi/try_gpi/gspc-gromovwitten/build_dir/template
CXXFLAGS += -I/home/atraore/gpi/try_gpi/gspc-gromovwitten/template
CXXFLAGS += -I/home/atraore/gpi/try_gpi/gspc-gromovwitten/template/src
CXXFLAGS += -I/home/atraore/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/gpi-space-24.12-jz6b4m6ql54fmhkpq6gbico2neic3kd5/include
CXXFLAGS += -I/home/atraore/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/gpi-space-24.12-jz6b4m6ql54fmhkpq6gbico2neic3kd5/external/boost/include
