LDFLAGS += -L/home/atraore/gpi/try_gpi/gspc-gromovwitten/build_dir
LDFLAGS += -L/home/atraore/gpi/try_gpi/gspc-gromovwitten/build_dir/src/util-generic
LDFLAGS += -Wl,-rpath='$$ORIGIN'
LDFLAGS += -Wl,-rpath='/home/atraore/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/gpi-space-24.12-jz6b4m6ql54fmhkpq6gbico2neic3kd5/lib'
LDFLAGS += -Wl,-rpath='/home/atraore/singular-gpispace/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/gpi-space-24.12-jz6b4m6ql54fmhkpq6gbico2neic3kd5/external/boost/lib'
